language: rust
rust:
  - 1.39.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true
script:
  - cargo clean
  - cargo test --verbose --features dumb_terminal