[package]
name = "bunyan_view"
version = "0.1.0"
authors = ["Elijah Zupancic <elijah@zupancic.name>"]
edition = "2018"

[features]
# this preserves the ordering of json
default = ["serde_json/preserve_order"]

# this effectively enable the feature `no-color` of colored when testing with
# `cargo test --feature dumb_terminal`
dumb_terminal = ["colored/no-color"]

[lib]
name = "bunyan_view"
path = "src/lib.rs"

[[bin]]
name = "bunyan"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"
chrono = "0.4"
serde = "1.0.102"
serde_json = "1.0.41"
serde_derive = "1.0.102"
httpstatus = "0.1.0"
flate2 = "1.0.13"
colored = "1.9.0"
pager = "0.15.0"

[dev-dependencies]
bytes = "0.4.12"
pretty_assertions = "0.6.1"