FROM rust:slim-buster

RUN set -eux \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get -qq update; \
    apt-get -qq install --yes --no-install-recommends --no-install-suggests \
        ca-certificates \
        gzip \
        grep \
        gawk \
        sed \
        make; \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*;