name: Build and Publish Binaries
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-experimental

jobs:
  build-linux-packages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: container-all-packages
        run: make container-all-packages
      - name: upload linux packages
        uses: actions/upload-artifact@v3
        with:
          name: linux-packages
          retention-days: 1
          path: target/dist/
  build-macos-packages:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: macos-packages
        run: gmake all-packages
      - name: upload MacOS packages
        uses: actions/upload-artifact@v3
        with:
          name: macos-packages
          retention-days: 1
          path: target/dist/
  build-supplemental-files:
    needs:
      - build-linux-packages
      - build-macos-packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download linux packages
        uses: actions/download-artifact@v3
        with:
          name: linux-packages
          path: target/dist/
      - name: download macos packages
        uses: actions/download-artifact@v3
        with:
          name: macos-packages
          path: target/dist/
      - name: checksum
        run: make checksums
      - name: release-notes
        run: make release-notes
      - name: homebrew-package
        run: make homebrew-package