name: Build and Publish Binaries
on:
  push:
    branches:
      - release-v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-linux-packages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: container-all-packages
        run: make container-all-packages
      - name: upload linux packages
        uses: actions/upload-artifact@v3
        with:
          name: linux-packages
          retention-days: 1
          path: target/dist/
  build-macos-packages:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: install x86_64-apple-darwin and aarch64-apple-darwin targets
        run: rustup target install x86_64-apple-darwin aarch64-apple-darwin
      - name: install latest gnu make version
        run: brew install make
      - name: macos-packages
        run: gmake gz-packages
      - name: upload MacOS packages
        uses: actions/upload-artifact@v3
        with:
          name: macos-packages
          retention-days: 1
          path: target/dist/
  build-supplemental-files-and-release:
    needs:
      - build-linux-packages
      - build-macos-packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download linux packages
        uses: actions/download-artifact@v3
        with:
          name: linux-packages
          path: target/dist/
      - name: download macos packages
        uses: actions/download-artifact@v3
        with:
          name: macos-packages
          path: target/dist/
      - name: checksum
        run: make checksums
      - name: output checksums
        run: cat target/dist/SHA256SUMS
      - name: release-notes
        run: make release-notes
      - name: homebrew-package
        run: make homebrew-packages
      - name: assign git user
        run: |
          git config user.name 'Github Action'
          git config user.email 'dekobon@users.noreply.github.com'
      - name: do release
        run: make gh-make-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}